// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0JgMgrZUl7Q5FuYV7906OAJ77eYHYbjg',
    appId: '1:180403447759:web:8fa7c815a24508fd5994ba',
    messagingSenderId: '180403447759',
    projectId: 'universidades-5cc96',
    authDomain: 'universidades-5cc96.firebaseapp.com',
    storageBucket: 'universidades-5cc96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_wQbGqgXc7CsnFKeR0pmvvoF0a7ZGoqc',
    appId: '1:180403447759:android:d2882ccea08231a85994ba',
    messagingSenderId: '180403447759',
    projectId: 'universidades-5cc96',
    storageBucket: 'universidades-5cc96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAPBi4LM3iNEOWp9rI8gu5Zq3RbcpbLRU',
    appId: '1:180403447759:ios:c030ad83f75d256f5994ba',
    messagingSenderId: '180403447759',
    projectId: 'universidades-5cc96',
    storageBucket: 'universidades-5cc96.firebasestorage.app',
    iosBundleId: 'com.example.cursoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAPBi4LM3iNEOWp9rI8gu5Zq3RbcpbLRU',
    appId: '1:180403447759:ios:c030ad83f75d256f5994ba',
    messagingSenderId: '180403447759',
    projectId: 'universidades-5cc96',
    storageBucket: 'universidades-5cc96.firebasestorage.app',
    iosBundleId: 'com.example.cursoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0JgMgrZUl7Q5FuYV7906OAJ77eYHYbjg',
    appId: '1:180403447759:web:34b158c8659382e15994ba',
    messagingSenderId: '180403447759',
    projectId: 'universidades-5cc96',
    authDomain: 'universidades-5cc96.firebaseapp.com',
    storageBucket: 'universidades-5cc96.firebasestorage.app',
  );
}
